---
config:
  theme: redux
  look: classic
  layout: elk
---
flowchart TB
    SC(("Stoney Coin<br>1000 Coins @ $1.0<br>3% Staking Bonus<br> Effort and Faith reward")) --- AB["Andy Boyd: CEO<br>Visionary, Economics, Charisma, Biz accumen<br>799 SC"]
    AB -.-> SP["Spencer Post: Consultant<br>Psychology, Econ, Cluster Computing<br>1 SC"]
    AB --- RB["Russle Baldridge: CTO<br>Technical, Hardware, Software<br>150 SC"] & W["Weston: Technical Advisor<br>Software, Server Setup<br>50 SC"]
    RB --- TBD1["TBD: Software Tech"]
    W --- TBD2["TBD: Server Maintenance"]
   
